### ISSUE TITLE
租房历史成交数据

### ISSUE THREAD

**Issue by EMingZ** [imlinchun/LianJia-API-Spide#1]
您好，请问可以爬取租房的历史已成交数据吗？

**Comment by imlinchun** [comment]
> 您好，请问可以爬取租房的历史已成交数据吗？
可以，手机APP上显示的所有数据，都可以抓到。调整相应的接口地址和参数即可

**Comment by NET86** [comment]
> 您好，请问可以爬取租房的历史已成交数据吗？

可以，手机APP上显示的所有数据，都可以抓到。调整相应的接口地址和参数即可
